#!/bin/python3
# Script Name:                 Python scrip
# Author:                       Akah 
# Date of latest revision:      09/07/2023
# Purpose:                    

import psutil

def get_system_info():
  """Gets system information using Psutil."""

  # Get the time spent by normal processes executing in user mode.
  user_time = psutil.cpu_times().user

  # Get the time spent by processes executing in kernel mode.
  kernel_time = psutil.cpu_times().system

  # Get the time when system was idle.
  idle_time = psutil.cpu_times().idle

  # Get the time spent by priority processes executing in user mode.
  priority_user_time = psutil.cpu_times(percpu=True)[0].user

  # Get the time spent waiting for I/O to complete.
  iowait_time = psutil.cpu_times().iowait

  # Get the time spent for servicing hardware interrupts.
  interrupts_time = psutil.cpu_times().interrupt

  # Get the time spent for servicing software interrupts.
  softirqs_time = psutil.cpu_times().softirq

  # Get the time spent by other operating systems running in a virtualized environment.
  guest_time = psutil.cpu_times().guest

  # Get the time spent running a virtual CPU for guest operating systems under the control of the Linux kernel.
  guest_nice_time = psutil.cpu_times().guest_nice

  return {
      "user_time": user_time,
      "kernel_time": kernel_time,
      "idle_time": idle_time,
      "priority_user_time": priority_user_time,
      "iowait_time": iowait_time,
      "interrupts_time": interrupts_time,
      "softirqs_time": softirqs_time,
      "guest_time": guest_time,
      "guest_nice_time": guest_nice_time,
  }


if __name__ == "__main__":
  system_info = get_system_info()
  print(system_info)












